Replace building stemcell binary in tasks with s3 resource.

diff --git a/bin/test-unit b/bin/test-unit
--- a/bin/test-unit
+++ b/bin/test-unit
@@ -1,1 +1,29 @@
-test_unit
+#!/bin/bash
+
+(
+  set -e
+
+  function printStatus {
+      if [ $? -eq 0 ]; then
+          echo -e "\nSWEET SUITE SUCCESS"
+      else
+          echo -e "\nSUITE FAILURE"
+      fi
+  }
+
+  trap printStatus EXIT
+
+  export BMP_UT_OUTPUT=False
+
+  echo -e "\n Cleaning build artifacts..."
+  go clean
+
+  echo -e "\n Formatting packages..."
+  go fmt ./...
+
+  echo -e "\n Unit Testing packages:"
+  ginkgo -r -p --noisyPendings --skipPackage=integration
+
+  echo -e "\n Vetting packages for potential issues..."
+  go tool vet main config cmds common integration
+)
